name: check_list_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get: ^4.6.6
  logger: ^2.4.0
  quickalert: ^1.1.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.3
  keyboard_dismisser: ^3.0.0
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0
  syncfusion_flutter_gauges: ^26.2.8
  flag: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  flutter_launcher_icons: "^0.13.1"
  hive_test: ^1.0.1
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/font/
    - assets/icon/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat/Montserrat-Regular.ttf
        - asset: assets/font/Montserrat/Montserrat-Bold.ttf
          weight: 700  # FontWeight.w700 for bold
        - asset: assets/font/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
          style: italic

    - family: Hanuman
      fonts:
        - asset: assets/font/Hanuman/Hanuman-Regular.ttf
        - asset: assets/font/Hanuman/Hanuman-Bold.ttf
          weight: 700  # FontWeight.w700 for bold
        - asset: assets/font/Hanuman/Hanuman-Black.ttf

flutter_launcher_icons:
  image_path_android: "assets/icon/logo710x599.png"
  image_path_ios: "assets/icon/logo1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/icon/background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#607D8B"
