import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive/hive.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'gen/todo_model.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'gen/todo_model.g.dart';

const String todoHiveBox = "todo_hive_box";
const String todoHiveKey = "todo_hive_key";

@unfreezed
class TodoModel with _$TodoModel {
  // ignore: invalid_annotation_target
  @JsonSerializable(fieldRename: FieldRename.none)
  @HiveType(typeId: 0) // HiveType annotation to generate the adapter
  factory TodoModel({
    @HiveField(0) String? title,
    @HiveField(1) String? description,
    @HiveField(2) @Default(false) bool isPriority,
    @HiveField(3) DateTime? createdDate,
    @HiveField(4) DateTime? updatedDate,
    @HiveField(5) @Default(false) bool isCompleted,
  }) = _TodoModel;

  factory TodoModel.fromJson(Map<String, Object?> json) =>
      _$TodoModelFromJson(json);
}
